#----------------------------------------------------------------------#
#       This is a docker-compose file to build and run our services    #
#----------------------------------------------------------------------#
version: "3.3"
services: 
  api:
    build:
      context: ../serveur
    image: api:1.0
    deploy:
      replicas: 1
    ports:
      - 4012:10010
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   - /etc/nginx:/app/src
    #   - /root/src/programme-fidelite/serveur:/src/app
    restart: always
    healthcheck:
      test: curl -sS 127.0.0.1:10010 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  front:
    image: nginx
    volumes:
      - ../app/build:/usr/share/nginx/html
      - ../serveur/default.conf:/etc/nginx/conf.d/default.conf
      - /srv/docker/sites-enabled:/etc/nginx/sites-enabled
    ports: 
      - 4011:80
      # - 4013:443
    restart: always
  autoheal: # <-- Our healing expert
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
